######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 22 20:34:52 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CanvasState.h CanvasStateData.h widget.h window.h
SOURCES += CanvasState.cpp CanvasStateData.cpp main.cpp widget.cpp window.cpp
